<!--
  ~ Copyright The RESTEasy Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.resteasy.vertx</groupId>
        <artifactId>resteasy-vertx-parent</artifactId>
        <version>2.0.0.Beta2-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>resteasy-vertx-cdi</artifactId>
    <packaging>jar</packaging>

    <name>RESTEasy Vert.x CDI</name>
    <description>CDI integration for RESTEasy Vert.x Embedded Server</description>

    <properties />

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.resteasy.vertx</groupId>
                <artifactId>resteasy-vertx-project-bom</artifactId>
                <version>2.0.0.Beta2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>dev.resteasy.vertx</groupId>
                <artifactId>resteasy-vertx-test-bom</artifactId>
                <version>2.0.0.Beta2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>dev.resteasy.vertx</groupId>
            <artifactId>resteasy-vertx-api</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.resteasy.vertx</groupId>
            <artifactId>resteasy-vertx-embedded-server</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging-annotations</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se-core</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>dev.resteasy.junit.extension</groupId>
            <artifactId>resteasy-junit-extension</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.resteasy.vertx</groupId>
            <artifactId>resteasy-vertx-client</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-embedded-server-tests</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Jakarta JSON Processing implementation -->
        <dependency>
            <groupId>org.eclipse.parsson</groupId>
            <artifactId>parsson</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <dependenciesToScan>org.jboss.resteasy:resteasy-embedded-server-tests</dependenciesToScan>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
