<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The RESTEasy Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.resteasy.vertx</groupId>
        <artifactId>resteasy-vertx-parent</artifactId>
        <version>2.0.0.Beta2-SNAPSHOT</version>
    </parent>

    <artifactId>resteasy-vertx-api</artifactId>
    <packaging>jar</packaging>

    <name>RESTEasy Vert.x API</name>
    <description>RESTEasy Vert.x API</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.resteasy.vertx</groupId>
                <artifactId>resteasy-vertx-project-bom</artifactId>
                <version>2.0.0.Beta2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>dev.resteasy.vertx</groupId>
                <artifactId>resteasy-vertx-test-bom</artifactId>
                <version>2.0.0.Beta2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging-annotations</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-core</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <classifier>tests</classifier>
            <scope>test</scope>
            <type>test-jar</type>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
